### PR TITLE
CapstoneProject- Build personal portfolio

### PR DESCRIPTION
**Pull request by MasomRezaie**
This project is a detailed display of my web development skills, experiences, and achievements. It holds the code and resources for my personal portfolio website, featuring a range of projects, case studies, and blog posts that illustrate my web development expertise. The portfolio is crafted to give an overview of my professional path, highlighting my successes and showcasing my skills.
This project serves as a guide for developers, contributors, and users to understand the architecture, implementation details, and usage for the project. This project is built by html, css and Javascript. Trough creating this repository, users will learn the html,css and Javascript that how style and get functions to a webpage.
This project has four sections:
1. Header: This section is about a short bio of me. 
2. About Me: This section provide information about me, my works, expaiences, skills, and achivemnets. 
3. Projects: This section provide my projects details and live link.
4. Contact US: Through this section others can contact with me.
5. 
Capture

### CODE REVIEW

**Comment by FarwaMuhibZada** [comment]
@MasomRezaie !
status: required changes 
✔️you did a great job
✔️Linter set up correctly for this repository.
✔️Linter result are green.
✔️There are no custom changes to linter config.
✔️you used correct GitHub Flow
✔️README file is descriptive.
✔️Commit messages are meaningful.
✔️Pull Request have a descriptive title explaining what changes are inside.
your app functionality working well
❌your design is not same as figma design   
❌your  deployment link does not work 









Capture
you added the different back ground color in about me and contact us sections that is not matching with the color of figma design try to use same color as figma .


 
Capture3
size of icons are not the same as figma try to make it look like figma design especially whats app icon .
Capture3 
here is also the sizing and Icons have problem.


Capture2
in contact form try to use your form spree account to receive  the emails . 


Capturem
change the background color and also the text color.
modal
change the background color  of modal in both moble and desktop version.



😊happy coding !

**Comment by MasomRezaie** [comment]
@ahzamir, Hello sir hope you are doing well. my project is ready for review

**Comment by ahzamir** [comment]
@MasomRezaie 

- Please include your Figma design link on your README.md file and also in the reply to this comment, cause I couldn't find the exact design you used

**Comment by MasomRezaie** [comment]
@ahzamir , Sir  I added the figma design link to my Readme. md file

**Comment by ahzamir** [comment]
@MasomRezaie 

- Ask your partner @FarwaMuhibZada  to provide you with a complete code review again
  - She already reviewed your project and provided some feedbacks once but you need to get their approval before asking me for the feedback

**Comment by FarwaMuhibZada** [comment]
dear @MasomRezaie !
share your development link for reviewing you project

**Comment by FarwaMuhibZada** [comment]
@MasomRezaie ! I noticed that you merged your branch into development. I didn't have a chance to review or approve it yet. Could we coordinate next time before merging?"

**Review by FarwaMuhibZada — COMMENTED** [review]
@MasomRezaie !
status: required changes
✔️you did a great job
✔️Linter set up correctly for this repository.
✔️Linter result are green.
✔️There are no custom changes to linter config.
✔️you used correct GitHub Flow
✔️README file is descriptive.
✔️Commit messages are meaningful.
✔️Pull Request have a descriptive title explaining what changes are inside.
your app functionality working well
❌your design is not same as figma design
✔️your deployment link work
your icons are not same as figma design try to make it like figma design

that is your design
Capture44


try to make it like this 
Capture

**Pull request merged**
